theme: minima
exclude: [".idea", "infra", "vendor"]

title: "Konrad M. Otrębski"
description: ""
timezone: "UTC"

#google analytics settings

google_analytics: UA-119949005-1
url: "https://kmotrebski.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-feed

#below is "minima" theme customization

header_pages:
  - about.md

minima:
  date_format: "%Y-%m-%d %H:%M %Z"

show_excerpts: true

github_username: kmotrebski
linkedin_username: konradotrebski
twitter_username: kmotrebski
